#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import logging
import argparse

from fuse import FUSE

from pyS3fs.fs import S3fs

def _get_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("mountpoint", help="directory to mount the filesystem in")
    parser.add_argument("-l", "--log-level", type=str, default="INFO",
        choices=["INFO", "DEBUG"])
    parser.add_argument("-b", "--background", help="run in background",
        action="store_true")

    return parser.parse_args()

def run():
    args = _get_arguments()

    logging.getLogger().setLevel(
        logging.INFO if args.log_level == "INFO" else logging.DEBUG
    )

    fuse = FUSE(S3fs(), args.mountpoint, foreground=(True if not args.background else False))

if __name__ == "__main__":
    run()
